const companies = [
  "FARAKKA ACC LIMITED",
  "SANKRAIL AMBUJA LIMITED",
  "OCL BENGAL CEMENT WORKS",
  "BIRLA CORPORATION LIMITED",
  "BCL- GODAPIASAL TP",
  "JSW CEMENT LIMITED SALBONI",
  "JINDAL STEEL AND POWER LIMITED",
  "SANKRAIL ACC LIMITED",
  "FARAKKA AMBUJA CEMENT LIMITED"
];

export default companies;